[package]
name = "poll"
version = "1.0.0"
authors = []

[addresses]
poll = "0x100505ee40858fd846a9a3bf7d08deae07a47117027dec4319cb77e0bba51b12"
pulse = "0x69c7c6752b3426e00fec646270e5b7e9f0efa18bddbd7f112a8e84f7fbe3f737"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "e85553104911152d800fa2c32f7ef0d80daf60b9"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.pulse]
local = "../pulse"

[dev-dependencies]
