[package]
name = "contracts"
version = "1.0.0"
authors = []

[addresses]
contracts = "0x742753ef60c4eb12c69cdbf01472cf2cad9d0781bd267278f4ca83e0c19c142f"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "e85553104911152d800fa2c32f7ef0d80daf60b9"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
